title: "Moola Siseho Mutondo"
description: "Plant Geneticist | Astrobiology Explorer | Advocate for Science Innovation in Africa"
baseurl: "/bioscience"
url: "https://dr.moolamutondo.me"
theme: minima
author: Moola S. Mutondo
